spring: 
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/DB?user=root&password=myPassword
        username: mariadb
        password: mariadb